language: python
python:
  - "2.7"

install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels anaconda
  - conda config --add channels workflowconversion

  - git clone https://github.com/WorkflowConversion/CTDopts $HOME/CTDopts
  - cd $HOME/CTDopts
  - python setup.py install 
  - conda install -c conda-forge lxml
  - conda install -c conda-forge ruamel.yaml 
  - conda install libxml2
  - cd $TRAVIS_BUILD_DIR
  - python setup.py install

  - conda install coverage green codecov

script:
  - python setup.py test

after_script:
- python -m codecov
